### ISSUE TITLE
Full history ?

### ISSUE THREAD

**Issue by JuCarm** [ymyke/tessa#10]
I'd love to have an option (argument ?) to get the full price history.
I have 2 use cases :
- I want the full price history, not just the last 19 years (e.g. long term comparison of asset returns)
- I want the full price history (less than 19 years), but I don't know when the price history begins (e.g. a new instrument e.g. an ETF).

**Comment by ymyke** [comment]
There's no function parameter for this but you can adjust the constant that is used like so:

```python
import tessa
tessa.investing.MIN_FROM_DATE = "01/01/1960"
# All queries will now use this ^ as a starting date...
res = tessa.price_history("AAPL", "stock", country="united states")
```

Caveat: investpy splits requests into sub-requests covering 19 years behind the scenes. If you run a lot of queries with an earlier start date in short order, you run the risk of triggering investing.com's rate limiting, producing 429 errors.

**Comment by ymyke** [comment]
Re caveat: If you need to run a lot of requests, consider using the low-level rate limiter: https://github.com/ymyke/tessa/blob/master/tessa/low_level_rate_limiter.py 

It'll rate-limit on the level of the `requests` module.
