### ISSUE TITLE
Q&A - Is it possible to get a symbol by an ISIN?

### ISSUE THREAD

**Issue by ixidion** [ymyke/tessa#12]
Hi, I just came from investpy. I used it to get the symbol by an ISIN. Is this possible with tessa at the moment?

**Comment by ymyke** [comment]
Yes, as long as Yahoo Finance finds something meaningful with the ISIN.

Example for ARKG:

```python
from tessa import Symbol
s = Symbol("US00214Q3020")
s.price_latest()
```

**Comment by ixidion** [comment]
Thanks, I got it to work by building it manually. Because the Python Requirement for the latest version is <3.10. I got 0.3.0 in the first place from pip. Maybe you can check.
Well, in the end, I had to stick to yfinance directly, because I needed the exchange, not only the price.

**Comment by ymyke** [comment]
Thanks!

1. What was/is the problem with <3.10? Can you elaborate?
2. What is your use case with the exchange? Maybe there's a feature idea in there for future releases?

**Comment by ixidion** [comment]
1.  See [Requirements Tessa](https://pypi.org/project/tessa/) -> Requires: Python >=3.7.13, <3.10 
Python 3.10.x ist the most recent python version, which I can't be used with tessa. Pip will refuse to install it and therefore dl the 0.3.0 version, which has <4.0
2. I need to get the exchange and symbol for a given ISIN to forge a watchlist in Tradingview, e.g. an entry looks like: NYSE:WWE

**Comment by ixidion** [comment]
1: Thanks for clarification.
2: Yes, would be a good idea to have the original structure as well for such cases.
