### ISSUE TITLE
Historical Data - Bonds

### ISSUE THREAD

**Issue by maykon17** [ymyke/tessa#21]
Hi there! How could I get global bonds yields data (example: Germany 10Y) with tessa? I've tried to search some symbols, but I got a Exception error. Thanks in advance!

**Comment by ymyke** [comment]
Hi! Is that ticker on Yahoo Finance? Can you give me the url and the search query to find it?

**Comment by maykon17** [comment]
It is not available on Yahoo Finance, but on Investing. I know there was a number of problems with investpy and did not find bonds data in another library.

**Comment by ymyke** [comment]
tessa currently only exposes Y Finance and Coingecko. Investpy is no longer available unfortunatley, see https://github.com/ymyke/tessa?tab=readme-ov-file#on-investpy-as-a-data-source

**Comment by maykon17** [comment]
Yeah, I know. But could you suggest other way to collect bonds data?

**Comment by ymyke** [comment]
I don't know unfortunately.

**Comment by maykon17** [comment]
No problem, thanks!
